chapter09/myshop/cart/urls.py
#! /usr/bin/python3
# -*- coding:utf-8 -*-
# @Time: 2022/4/12
# @Author: Lingchen
# @Prescription:
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    # 购物车url.
    path('', views.cart_detail, name='cart_detail'),
    # 添加商品到购物车.
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    # 删除购物车中商品.
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

chapter09/myshop/coupons/urls.py
#! /usr/bin/python3
# -*- coding:utf-8 -*-
# @Time: 2022/4/24
# @Author: Lingchen
# @Prescription:
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    # code url.
    path('apply/', views.coupon_apply, name='apply'),
]

chapter09/myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    # 购物车操作urls.
    path(_('cart/'), include('cart.urls', namespace='cart')),
    # 订单urls.
    path(_('orders/'), include('orders.urls', namespace='orders')),
    # 交易urls.
    path(_('payment/'), include('payment.urls', namespace='payment')),
    # 折扣urls.
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    # 翻译rosetta, urls.
    path('rosetta/', include('rosetta.urls')),
    # 商品urls.
    path('', include('shop.urls', namespace='shop')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chapter09/myshop/orders/urls.py
#! /usr/bin/python3
# -*- coding:utf-8 -*-
# @Time: 2022/4/13
# @Author: Lingchen
# @Prescription:
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views

app_name = 'orders'

urlpatterns = [
    # 订单创建.
    path(_('create/'), views.order_create, name='order_create'),
    # 自定制order管理页面.
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    # pdf导出.
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

chapter09/myshop/shop/urls.py
#! /usr/bin/python3
# -*- coding:utf-8 -*-
# @Time: 2022/4/11
# @Author: Lingchen
# @Prescription:
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    # 商品列表页面.
    path('', views.product_list, name='product_list'),
    # 以商品类别显示商品列表.
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    # 商品详细.
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

chapter09/myshop/cart/models.py
from django.db import models

# Create your models here.

chapter09/myshop/cart/forms.py
#! /usr/bin/python3
# -*- coding:utf-8 -*-
# @Time: 2022/4/12
# @Author: Lingchen
# @Prescription:
from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    """
    允许用户选择数量.
    """
    # 这允许用户选择1到20之间的数量. 使用coerce=int的TypedChoiceField字段将输入转换为整数.
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int,
                                      label=_('Quantity'))
    # 说明是否必须添加数量到此产品的购物车中的任何现有数量(False), 或是否必须用给定数量覆盖现有数量(True).
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

chapter09/myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm

# Create your views here.


@require_POST
def cart_add(request, product_id):
    """
    将产品添加到购物车或更新现有产品的数量.
    :param request:
    :param product_id:
    :return:
    """
    cart = Cart(request)

    product = get_object_or_404(Product, id=product_id)

    # 获取post方式中的数据form.
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        # 添加或者更新购物车中的商品.
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])

    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    """
    删除购物车中的商品.
    :param request: 
    :param product_id: 
    :return: 
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    cart.remove(product)

    return redirect('cart:cart_detail')


def cart_detail(request):
    """
    显示购物车商品信息.
    :param request:
    :return:
    """
    cart = Cart(request)

    # 为购物车中的每个商品创建CartAddProductForm实例，以允许更改产品数量.
    # 使用当前物料数量初始化表单，并将覆盖字段设置为True，这样当您将表单提交到cart_add视图时，当前数量将替换为新数量.
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True})

    coupon_apply_form = CouponApplyForm()

    return render(request,
                  'cart/detail.html',
                  {'cart': cart,
                   'coupon_apply_form': coupon_apply_form})

chapter09/myshop/cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load i18n %}
{% load static %}

{% block title %}
  {% trans "Your shopping cart" %}
{% endblock %}

{% block content %}
  <h1>{% trans "Your shopping cart" %}</h1>

  <table class="cart">
    <thead>
      <tr>
        <th>{% trans "Image" %}</th>
        <th>{% trans "Product" %}</th>
        <th>{% trans "Quantity" %}</th>
        <th>{% trans "Remove" %}</th>
        <th>{% trans "Unit price" %}</th>
        <th>{% trans "Price" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
        <tr>
          <td>
            <a href="{{ product.get_absolute_url }}">
              <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
            </a>
          </td>
          <td>
            {{ product.name }}
          </td>
          <td>
            <!--{{ item.quantity }}-->
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
              {{ item.update_quantity_form.quantity }}
              {{ item.update_quantity_form.override }}
              {% csrf_token %}
              <input type="submit" value="{% trans "Update" %}" />
            </form>
          </td>
          <td>
            <form action="{% url 'cart:cart_remove' product.id %}" method="post">
              <input type="submit" value="{% trans "remove" %}">
              {% csrf_token %}
            </form>
          </td>
          <td class="num">
            ¥{{ item.price }}
          </td>
          <td class="num">
            ¥{{ item.total_price }}
        </tr>
        {% endwith %}
      {% endfor %}
      <!--折扣信息.-->
      {% if cart.coupon %}
        <tr class="subtotal">
          <td>{% trans "Subtotal" %}</td>
          <td colspan="4"></td>
          <td class="num">¥{{ cart.get_total_price | floatformat:2}}</td>
        </tr>
        <tr>
          {% blocktrans with code=cart.coupon.code disabled=cart.coupon.discount %}
            <td>
              "{{ code }}" coupon ({{ discount }}% off)
            </td>
          {% endblocktrans %}
          <td colspan="4"></td>
          <td class="num neg">
            - ¥{{ cart.get_discount | floatformat:2 }}
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>{% trans Total %}</td>
        <td colspan="4"></td>
        <!--<td class="num">¥{{ cart.get_total_price }}</td>-->
        <td class="num">¥{{ cart.get_total_price_after_discount | floatformat:2 }}</td>
      </tr>
    </tbody>
  </table>

  <p>Apply a coupon:</p>
  <form action="{% url 'coupons:apply' %}" method="post">
    {{ coupon_apply_form }}
    <input type="submit" value="Apply">
    {% csrf_token %}
  </form>

  <p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">{% trans "Continue shopping" %}</a>
    <a href="{% url 'orders:order_create' %}" class="button">{% trans "Checkout" %}</a></a>
    <!--<a href="#" class="button">Check out</a>-->
  </p>
{% endblock %}