chapter03/mysite/blog/urls.py
#! /usr/bin/python3
# -*- coding:utf-8 -*-
# @Time: 2022/3/26
# @Author: Lingchen
# @Prescription:
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # post列表页面.
    path('', views.post_list, name='post_list'),
    # 使用基于类的对象视图.
    # path('', views.PostListView.as_view(), name='post_list'),
    # post详细页面.
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    # 邮件.
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    # 查询带tag的post的列表.
    # slug path转换器，将参数匹配为带有ASCII字母或数字的小写字符串，再加上连字符和下划线字符.
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # feeds.
    path('feed/', LatestPostsFeed(), name='post_feed'),
    # 搜索post.
    path('search', views.post_search, name='post_search'),
]

chapter03/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    # 配置网站导航.
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

chapter03/mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.


class PublishedManager(models.Manager):
    """
    创建Model管理器.
    """
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset()\
                          .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    # CharField -> Varchar
    title = models.CharField(max_length=250)
    # 这是一个用于URL的字段。slug是一个短标签, 只包含字母、数字、下划线或连字符的.
    # 你将使用slug字段可以为你的博客帖子创建漂亮的、对搜索引擎友好的URL.
    # 您已将unique_for_date参数添加到此字段，以便可以使用发布日期和slug为帖子构建URL.
    # django的防止多个帖子在给定日期出现相同的问题.
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    # many to one 关系. 一个用户可以写多个Posts. 级联.
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    # TextField -> Text.
    body = models.TextField()
    # DateTimeField -> Datetime.
    publish = models.DateTimeField(default=timezone.now)
    # auto_now_add 自动创建时间.
    created = models.DateTimeField(auto_now_add=True)
    # auto_now 更新时自动更新时间.
    updated = models.DateTimeField(auto_now=True)
    # 类似类型转换.
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager()
    published = PublishedManager()
    # 标签管理. 标签管理器将允许您添加、检索和删除Post对象中的标签.
    tags = TaggableManager()

    class Meta:
        """
        按publish字段按默认降序对结果进行排序.
        """
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        获取详细post的url路径.
        :return:
        """
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):
    """
    评价类.
    """
    # comment vs post: many to one的关系.
    # related_name='comments': 检索的关联名称. 1) comment.post. 2) post.comments.all()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # active布尔字段，您将使用该字段手动停用不适当的评论.
    active = models.BooleanField(default=True)

    class Meta:
        # 默认情况下，可以使用创建的字段按时间顺序对注释进行排序.
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

chapter03/mysite/blog/forms.py
#! /usr/bin/python3
# -*- coding:utf-8 -*-
# @Time: 2022/3/27
# @Author: Lingchen
# @Prescription:
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    """
    创建email的提交表单.
    """
    # CharField -> input text.
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    # CharField + widget -> input textarea.
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    """
    根据Model:Comment来创建一个动态的Form.
    """
    class Meta:
        model = Comment
        # 表单元素的限定.
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    """
    搜索form.
    """
    query = forms.CharField()

chapter03/mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from taggit.models import Tag
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm


# Create your views here.


def post_list(request, tag_slug=None):
    """
    获取post列表, 过滤状态为published.
    添加特定tag的关联功能.
    :param request:
    :param tag_slug: 默认值为None, url中传tag的值.
    :return:
    """
    objects_list = Post.published.all()
    # 标签处理.
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        # 一个post可以拥有多个tag, 一个tag可以从属于多个post.
        # 筛选tags. many to many关系.
        objects_list = objects_list.filter(tags__in=[tag])

    # 分页. 每页3个post.
    paginator = Paginator(objects_list, 3)
    # 获取当前页面数.
    page = request.GET.get('page')
    # print('page: ' + str(page))
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # 如果页面不是整数，则交付第一页.
        posts = paginator.page(1)
    except EmptyPage:
        # 如果页面超出范围，请提交最后一页结果.
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag': tag})


def post_detail(request, year, month, day, post):
    """
    获取post的详细信息.
    添加的post相关的comments信息.
    :param request:
    :param year:
    :param month:
    :param day:
    :param post:
    :return:
    """
    post = get_object_or_404(Post,
                             slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # 获取post相关的comments信息
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # 提交的comment处理.
        comment_form = CommentForm(data=request.POST)
        # 表单元素是否得到验证.
        if comment_form.is_valid():
            # 创建一个comment对象, 并不保存到db中.
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            # 保存到db.
            new_comment.save()
    else:
        # post页面初始时, 生成一个comment的form.
        comment_form = CommentForm()

    # 获取相似的posts.
    # 检索当前帖子标签的ID列表.
    # values_list是QuerySet返回带有给定项目值的元组.
    # 将flat=True传递给它，得到单个值，例如[1，2，3，…]而不是像[（1，），（2，），（3，）…]这样的一个元组.
    post_tags_ids = post.tags.values_list('id', flat=True)
    # 获取带这些的tag的posts, 排除自己.
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                  .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                                 .order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts})


def post_share(request, post_id):
    """
    通过id来检索post.
    :param request:
    :param post_id:
    :return:
    """
    # 通过ID检索到的具有"已发布"状态的post.
    post = get_object_or_404(Post, id=post_id, status='published')
    # 邮件发送成功flg.
    sent = False
    if request.method == 'POST':
        # 获取提交的email表单.
        form = EmailPostForm(request.POST)
        # 验证表单, 是否必入力, email是否正确等.
        if form.is_valid():
            # 获取表单数据.
            cd = form.cleaned_data
            # 发送Email....
            # post_url = request.build_absolute_url(post.get_absolute_url())
            post_url = request.build_absolute_uri(post.get_absolute_url())
            # 邮件主题.
            subject = f"{cd['name']} recommends you read " \
                      f"{post.title}"
            # 邮件信息
            message = f"Read {post.title} at {post_url} \n\n" \
                      f"{cd['name']} \'s comments: {cd['comments']}"
            # send_mail(subject, message, 'admin@admin.com', [cd['to']])
            send_mail(subject, message, cd['email'], [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


class PostListView(ListView):
    """
    1.使用特定的queryset，而不是检索所有对象.
    如果是queryset属性，则可以指定model=Post，Django将构建通用Post.objects.all().
    2.对查询结果使用上下文变量POST。默认变量是object_list
    3.如果您没有指定任何上下文对象名称对结果进行分页，每页显示三个对象使用自定义模板呈现页面.
    4.如果没有设置默认模板，ListView将使用blog/post_list.html.
    """
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_search(request):
    """
    post的搜索接口.
    :param request:
    :return:
    """
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            # 提取query字段.
            query = form.cleaned_data['query']
            # 使用标题和正文字段构建的自定义SearchVector实例搜索已发布的posts.
            # results = Post.published.annotate(
            #     search=SearchVector('title', 'body'),
            # ).filter(search=query)

            # 词干分析与排名.
            # search_vector = SearchVector('title', 'body')
            # 加权查询.
            # 对使用标题和正文构建的搜索向量应用不同的权重.
            # 默认权重为D、C、B和A，它们分别指数字0.1、0.2、0.4和1.0.
            # 将权重1.0应用于标题搜索向量，将权重0.4应用于正文向量.
            # search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            # search_query = SearchQuery(query)

            # 创建一个SearchQuery对象，按其过滤结果，并使用SearchRank按相关性排序结果.
            # results = Post.published.annotate(
            #     search=search_vector,
            #     rank=SearchRank(search_vector, search_query)
            # ).filter(search=search_query).order_by('-rank')

            # 标题匹配将优先于正文内容匹配. 过滤结果，只显示排名高于0.3的结果.
            # results = Post.published.annotate(
            #     rank=SearchRank(search_vector, search_query)
            # ).filter(rank__gte=0.3).order_by('-rank')

            # 三元相似性搜索.
            results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query),
            ).filter(similarity__gt=0.1).order_by('-similarity')

    return render(request, 'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

chapter03/mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

<!--加载自己定制的tag.-->
{% load blog_tags %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published: {{ post.publish }} by {{ post.author }}
  </p>
  <!--{{ post.body | linebreaks }}-->

  <!--使用markdown过滤器, 渲染markdown形式的文本为html形式的文本.-->
  {{ post.body | markdown }}
  <p>
    <!-- 使用url. 需要先声明: app_name:view_name.-->
    <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
  </p>

  <!--类似post推荐部分.-->
  <h2>Similar posts</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
      There are no similar posts yet.
  {% endfor %}

  <!--comments部分.-->
  <!--执行QuerySet语句, 声明一个新的变量, 在with语句块中这个变量可用.-->
  {% with comments.count as total_comments %}
    <h2>
      <!--使用复数模板过滤器:pluralize显示单词“comment”的复数sufix，具体取决于总的comments值.-->
      <!--若结果不为1, 返回一个字符:s. 0 comments, 1 comment, or N comments.-->
      {{ total_comments }} comment{{ total_comments | pluralize }}
    </h2>
  {% endwith %}

  <!--展示comment功能.-->
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
      </p>
      {{ comment.body | linebreaks }}
    </div>
  {% empty %}
    <p>There are no comments yet.</p>
  {% endfor %}

  <!--新建comment功能.-->
  {% if new_comment %}
    <h2>Your comment has been added.</h2>
  {% else %}
    <h2>Add a comment</h2>
    <form method="post">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p>
        <input type="submit" value="Add comment">
      </p>
    </form>
  {% endif %}

{% endblock %}

chapter03/mysite/blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

chapter03/mysite/blog/templates/blog/post/list.html
<!--从blog/base.html继承模板.-->
{% extends "blog/base.html" %}

<!--加载自己定制的tag.-->
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
  <h1>My Blog</h1>
  <!--标签管理.-->
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </h2>
    <!--添加post的标签.-->
    <p class="tags">
      <!--Tags: {{ post.tags.all | join:", " }}-->
      Tags:
        {% for tag in post.tags.all %}
          <!--添加带有tag查询的post的列表.-->
          <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
          {% if not forloop.last %},
          {% endif %}
        {% endfor %}
    </p>

    <p class="date">
      Published: {{ post.publish }} by {{ post.author }}
    </p>
    <!--truncatewords将值截断为指定的字数，linebreaks将输出转换为HTML换行符. -->
    <!--您可以连接任意多个模板过滤器；每一个都将应用于前一个生成的输出-->
    <!--{{ post.body|truncatewords:30|linebreaks }}-->

    <!--truncatewords_html过滤器会在一定数量的单词后截断字符串，避免未关闭的html标记. -->
    {{ post.body | markdown | truncatewords_html:30 }}
  {% endfor %}

  <!--设置分页.-->
  <!--由于传递给模板的页面对象称为posts，因此可以在post列表模板中包含分页模板，并传递参数以正确呈现它.-->
  {% include "blog/pagination.html" with page=posts %}
  <!--使用类对象的页面视图来传值.-->
  <!--{% include "blog/pagination.html" with page=page_obj %}-->
{% endblock %}

chapter03/mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>

    <h3>
      {% with results.count as total_results %}
      Found {{ total_results }} result{{ total_results | pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
      {{ post.body | markdown | truncatewords_html:5 }}
      {% empty %}
        <p>There are no results for your query.</p>
    {% endfor %}
    <p>
      <a href="{% url 'blog:post_search' %}">Search again</a>
    </p>
  {% else %}
    <h1>Search for posts</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search" />
    </form>
  {% endif %}
{% endblock %}

chapter03/mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %} Share a post {% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully send</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <!--设置form表单. 提交方式为post.-->
    <form method="post">
      <!--将form是的表单元素渲染成p标签中的元素.-->
      <!--类似的as_ul. as_table.-->
      {{ form.as_p }}
      <!--自动生成的一个token, 防止跨域csrf攻击.-->
      {% csrf_token %}
      <input type="submit" valye="Send a email">
    </form>
  {% endif %}
{% endblock %}